version: '3.2'

services:
  db:
    image: mysql
    container_name: mysql_eshop
    stop_signal: SIGKILL
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./sql-scripts/:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 7753191
      MYSQL_DATABASE: eshop
      
  rest_demo_service:
    container_name: eshop_rest_service
    build: ./
    working_dir: /app
    volumes:
    - ./:/app
    - ~/.m2:/root/.m2
    tty: true
    ports:
    - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db

networks:
  default:
    external:
      name: rest_network